# Generated by Django 5.2.1 on 2025-07-04 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cart_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='added_on',
        ),
    ]
